replicaCount: 1

image:
  repository: tonutilisateurdocker/devop-frontend
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false
