replicaCount: 3

image:
  repository: chouroukchaker/frontendevops
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  - name: REACT_APP_SERVER_URL
    value: http://server:5000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: mern-app.local
      paths:
        - path: /
  tls: []

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
